spring.application.name=unidad10_APIRestSpringBoot

# Configuracion de la base de datos H2 (en memoria, usando las credenciales usadas en la unidad8_jpa)
spring.datasource.url=jdbc:h2:mem:jpa_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Habilitar la consola web de H2 para poder visualizar la base de datos (ruta: http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configuracion de JPA y Hibernate (replicando las properties de persistence.xml)
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
